

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


CREATE SCHEMA IF NOT EXISTS `provider-db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `provider-db` ;

DROP TABLE IF EXISTS `provider-db`.`date` ;

CREATE TABLE IF NOT EXISTS `provider-db`.`date` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `time` VARCHAR(5) NOT NULL,
  `day` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 79
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS `provider-db`.`provider` ;

CREATE TABLE IF NOT EXISTS `provider-db`.`provider` (
  `code` VARCHAR(4) NOT NULL,
  `provider` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


DROP TABLE IF EXISTS `provider-db`.`provider_date` ;

CREATE TABLE IF NOT EXISTS `provider-db`.`provider_date` (
  `id` INT(11) NOT NULL,
  `code` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`id`, `code`),
  INDEX `code` (`code` ASC) VISIBLE,
  CONSTRAINT `provider_date_ibfk_1`
    FOREIGN KEY (`code`)
    REFERENCES `provider-db`.`provider` (`code`),
  CONSTRAINT `provider_date_ibfk_2`
    FOREIGN KEY (`id`)
    REFERENCES `provider-db`.`date` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
